Repository datamweb/shield-oauth, pull requests merged in 2024-07, with the labels that each got.

#130 Fix: Dig deeper for an email address on Github
  src/Libraries/GithubOAuth.php
Labels: bug

#133 feat: Returns the user's email if the account is not found.
  src/Controllers/OAuthController.php
  src/Language/en/ShieldOAuthLang.php
  src/Language/fa/ShieldOAuthLang.php
  src/Language/fr/ShieldOAuthLang.php
  src/Language/id/ShieldOAuthLang.php
Labels: enhancement

#134 feat: Handles deauthentication actions by users.
  src/Controllers/OAuthController.php
  src/Language/en/ShieldOAuthLang.php
  src/Language/fa/ShieldOAuthLang.php
  src/Language/fr/ShieldOAuthLang.php
  src/Language/id/ShieldOAuthLang.php
Labels: enhancement

#136 chore: add auto-update-copyright-year github action
  .github/workflows/auto-update-copyright.yml
Labels: Github Action
